"use client";

/**
 * ReportExport — lets the user download the research report as Markdown.
 *
 * @param {{ result: Object, companyName: string }} props
 */

/**
 * Converts the verdict result object to a Markdown document.
 * @param {Object} result
 * @param {string} companyName
 * @returns {string}
 */
function toMarkdown(result, companyName) {
  const date = new Date(result.researchedAt || Date.now()).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const scorecardMd = result.scorecard
    ? Object.entries(result.scorecard)
        .map(([k, v]) => `| ${k} | ${v}/10 |`)
        .join("\n")
    : "";

  const sectionsMd = (result.sections || [])
    .map((s) => {
      const points = (s.keyPoints || []).map((p) => `- ${p}`).join("\n");
      const sources = (s.sources || [])
        .filter((src) => src.url)
        .map((src) => `- [${src.title}](${src.url})`)
        .join("\n");
      return `## ${s.aspect.charAt(0).toUpperCase() + s.aspect.slice(1)}\n\n${s.summary}\n\n${points}\n\n${sources ? `**Sources:**\n${sources}` : ""}`;
    })
    .join("\n\n---\n\n");

  return `# Verdict Research Report: ${companyName}

**Date:** ${date}  
**Verdict:** ${result.verdict}  
**Confidence:** ${result.confidence}%

---

## Executive Summary

${result.summary || "N/A"}

---

## Investment Scorecard

| Dimension | Score |
|-----------|-------|
${scorecardMd}

---

## For (Reasons to Invest)

${(result.prosFor || []).map((p) => `- ${p}`).join("\n")}

## Against (Reasons to Pass)

${(result.consAgainst || []).map((p) => `- ${p}`).join("\n")}

## Key Risks

${(result.risks || []).map((r) => `- ${r}`).join("\n")}

---

${sectionsMd}

---

*Generated by Verdict — AI Investment Research Agent*  
*Research is AI-generated and grounded in live web data. Not financial advice.*
`;
}

export default function ReportExport({ result, companyName }) {
  if (!result) return null;

  function handleDownload() {
    const md = toMarkdown(result, companyName);
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `verdict-${companyName.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <button
      id="download-report-btn"
      onClick={handleDownload}
      className="
        flex items-center gap-2
        px-4 py-2 rounded-xl
        border border-surface-3 bg-surface-1
        text-ink-subtle hover:text-ink-loud
        hover:border-brand-500/30 hover:bg-surface-2
        transition-all duration-200
        text-sm font-medium
      "
      title="Download Markdown report"
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      Export Report
    </button>
  );
}
